/* eslint-disable */
require('./404')
require('./chart')
require('./close')
require('./dentifying_code')
require('./dog')
require('./eye-open')
require('./eye')
require('./open')
require('./pageclose')
require('./Password')
require('./user')
require('./xiala')
